fixed all templates files not being copied
nhcarrigan/TSProGen pull request #27
Opened 2020-11-03 00:30 UTC by creepinson

# Pull Request

## Description:

 

I must have messed up the copyfiles command earlier which caused the previous pr to make it not generate all of the required files (only src/ was generated).  Sorry about this lol

Skywolf fixed the generation command for the files as well as removing the extra template/src/index.ts file, and I fixed concurrency problems so that it should generate node_modules after.

## Related Issue:

Closes #XXXXX

## Checklist

- Copyfiles command fixed
- Concurrency issue fixed
- Removed src/template/src/index.ts cuz it doesn't need to be there.

### Semantic Versioning

My pull request updates the version in the `package.json` based on the following:

- [ ] Major Update (X.\_._) - this PR introduces breaking changes.
- [ ] Minor Update (\_.X._) - this PR introduces new, but non-breaking, features.
- [ ] Patch Update (\_._.X) - this PR adds no new features (i.e. bug fixes, documentation updates)

2020-11-03 00:41 UTC, SkyWolf369 approved these changes

2020-11-03 00:43 UTC, nhcarrigan requested changes
One tweak. 

Additionally, what happened to the `src` directory generation? And the `index.ts` file generation? 🤔

2020-11-03 00:43 UTC, nhcarrigan commented on package.json
>      "build": "tsc",
```suggestion
  "scripts": {
    "prebuild": "rm -rf ./prod",
    "build": "tsc",
```

While we are in here, let's add a prebuild script to remove the existing `prod` directory - this'll prevent conflicts when building and publishing.

2020-11-03 00:46 UTC, SkyWolf369 approved these changes

2020-11-03 00:46 UTC, nhcarrigan approved these changes

2020-11-03 00:46 UTC, merged

2020-11-05 18:39 UTC, creepinson commented
About the src directory, skywolf said we didn't need it. I mean, its kind of true because you can just create a src folder yourself but I guess it would be nice to have that there.

2020-11-05 18:40 UTC, nhcarrigan commented
S'okay - I've merged a fix for it.

The `tsconfig.json` generates with a setting to compile from `src` into `prod`, so it's good to generate that folder (and the `index.ts` it contains) as part of the CLI command.